name: smart_campus_guide
description: "西南大学智能导览系统"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.0
  provider: ^6.1.0
  sqflite: ^2.3.0
  path: ^1.9.0
  dio: ^5.9.2
  # 地图（开源方案）
  flutter_map: ^7.0.2
  latlong2: ^0.9.1
  # 摄像头
  camera: ^0.11.1
  image_picker: ^1.1.2

  # 新增多媒体及UI依赖
  cached_network_image: ^3.3.1  # 网络图片缓存加载
  carousel_slider: ^5.1.2       # 高清图片轮播图
  video_player: ^2.8.2          # 核心视频播放能力
  chewie: ^1.7.5                # 封装好的视频播放器UI控制栏
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
