server:
  port: 8080
  address: 0.0.0.0  # 核心修改：开放监听电脑的所有网卡，允许安卓模拟器访问

spring:
  datasource:
    # 修改了 host(mysql6.sqlpub.com), 端口(3311) 以及 数据库名称(smart_campus_guide)
    url: jdbc:mysql://mysql6.sqlpub.com:3311/smart_campus_guide?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    # 修改了数据库账号
    username: scg_user
    # 修改了数据库密码
    password: GkwrbnAAU5cUpcTg
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 127.0.0.1
      port: 6379

logging:
  level:
    root: info